export const NEOGULIP_TEXTS = {
  NAME: "너굴잎",
  ROLE: "AI 사서",
  BETA_LABEL: "Beta",
  DESCRIPTION: "풀내음 가득한 책을 찾아드릴게요 🍃",
  LOADING_MESSAGES: [
    "나뭇잎 책갈피를 찾는 중이구리... 🍃",
    "숲속 도서관 서재를 뒤적적... 📚",
    "가을바람에 실려온 책 냄새를 맡는 중... 🍂",
    "따뜻한 코코아 한 잔 마시며 고르고 있어요 ☕",
    "거의 다 찾았어요! 조금만 기다려주세요구리! 🦝",
  ],
  ERROR: "죄송해요, 잠시 나뭇잎을 놓쳤네요. 다시 말씀해 주시겠어요? 🍃",
  WAITING_TITLE: "너굴잎이 대기 중이에요",
  WAITING_DESC_PREFIX: "왼쪽 채팅창에서 이야기를 들려주시면",
  WAITING_DESC_HIGHLIGHT: "인생 책",
  WAITING_DESC_SUFFIX: "을 찾아올게요! 🍃",
  SUCCESS_TITLE: '"찾았습니다구리! 🍃"',
  SUCCESS_DESC: "너굴잎이 엄선한 책들이에요.",
  ADD_TO_WISHLIST: "+ 위시리스트에 추가",
  RETRY_LINK: "다른 책도 찾아볼까요?",
  RESET_TITLE: "대화를 초기화하시겠어요? 🍃",
  RESET_DESC:
    "지금까지 나눈 대화와 추천받은 책 목록이 모두 사라지고, 너굴잎과 처음부터 다시 이야기를 시작하게 됩니다.",
  RESET_CONFIRM: "초기화할래구리!",
  RESET_CANCEL: "취소",
  NEW_SEARCH_TITLE: "새로운 책을 찾으시겠어요? 🍃",
  NEW_SEARCH_DESC:
    "현재 추천받은 책 목록이 사라집니다. 내 서재에 담지 않은 책은 다시 찾기 어려울 수 있어요!",
  NEW_SEARCH_CONFIRM: "새로 찾을래구리!",
  NEW_SEARCH_CANCEL: "더 볼래요",
  GREETING:
    "안녕하세요! 저는 책을 좋아하는 너굴잎이라고 해요! 🦝🍃\n어떤 이야기를 좋아하시나요? 요즘 기분은 어떠신가요?",
  LOGIN_CTA_TITLE: "로그인이 필요해요구리! 🔒",
  LOGIN_CTA_DESC: "너굴잎이 엄선한 책을 확인하려면\n로그인이 필요합니다.",
  LOGIN_BTN: "로그인하고 결과 보기 🍃",
} as const;
