export const API_PATHS = {
  auth: {
    login: (provider: "naver" | "kakao") => `/auth/${provider}`,
    logout: "/auth/logout",
    refresh: "/auth/refresh",
    emailRegister: "/auth/signup",
    emailLogin: "/auth/login",
  },
  user: {
    base: "/user",
    profile: "/user/profile",
    publicProfile: (handle: string) => `/user/profile/${handle}`,
    stats: "/user/stats",
    wishlist: "/user/wishlist",
    wishlistCheck: "/user/wishlist/check",
    wishlistStatus: "/user/wishlist/status",
    checkNickname: "/user/check-nickname",
  },
  book: {
    list: "/book-list",
    externalList: "/book/external/list",
    detail: "/book-detail",
    externalDetail: "/book/external/detail",
    sales: "/book/sales",
    sale: "/book/sale",
    mySales: "/user/my-sales",
    saleStatus: (saleId: number) => `/book/sales/${saleId}/status`,
    saleDetail: (saleId: string) => `/book/sales/${saleId}`,
    saleForEdit: (saleId: string | number) => `/book/sales/${saleId}/edit`,
    relatedSales: (isbn: string) => `/book/${isbn}/sales`,
    updateSale: (saleId: number) => `/book/sales/${saleId}`,
    deleteSale: (saleId: number) => `/book/sales/${saleId}`,
    recentSales: "/book/sales/recent",
    popularBooks: "/book/popular",
    recordView: (isbn: string) => `/book/${isbn}/view`,
    recordSaleView: (saleId: number) => `/book/sales/${saleId}/view`,
    popularSales: "/book/sales/popular",
    stats: (isbn: string) => `/book/${isbn}/stats`,
  },
  searchKeyword: {
    record: "/search-keywords",
    popular: "/search-keywords/popular",
  },
  art: {
    list: "/art-list",
    externalList: "/art/external/list",
    detail: (artId: string) => `/art-detail/${artId}`,
    externalDetail: (artId: string) => `/art/external/detail/${artId}`,
  },
  llm: {
    talk: "/llm/talk",
    summary: "/llm/book-summary",
  },
  chat: {
    rooms: "/chat/rooms",
    room: (roomId: number) => `/chat/rooms/${roomId}`,
    messages: (roomId: number) => `/chat/rooms/${roomId}/messages`,
    read: (roomId: number) => `/chat/rooms/${roomId}/read`,
  },
  comment: {
    base: "/comments",
    my: "/comments/my",
    detail: (id: number) => `/comments/${id}`,
    like: (id: number) => `/comments/${id}/like`,
  },
  notification: {
    base: "/notifications",
    read: (id: number) => `/notifications/${id}/read`,
    readAll: "/notifications/read-all",
    unreadCount: "/notifications/unread-count",
  },
  readingLog: {
    base: "/reading-logs",
    stats: "/reading-logs/stats",
    list: "/reading-logs/list",
    settings: "/reading-logs/settings",
    detail: (id: string) => `/reading-logs/${id}`,
    // ✅ 라운지 API 경로 추가
    loungeFeed: "/reading-logs/lounge",
    loungePopular: "/reading-logs/lounge/popular",
    loungeBookReaders: (isbn: string) => `/reading-logs/lounge/book/${isbn}/readers`,
  },
  review: {
    base: "/reviews",
    detail: (id: number | string) => `/reviews/${id}`,
    recordView: (id: number | string) => `/reviews/${id}/view`,
    edit: (id: number | string) => `/reviews/${id}/edit`,
    feeds: "/reviews/feeds",
    popular: "/reviews/popular",
    recommend: (id: number | string) => `/reviews/${id}/recommend`,
    myReaction: (id: number | string) => `/reviews/${id}/reaction`,
    toggleReaction: (id: number | string) => `/reviews/${id}/reactions`,
  },
  insights: {
    base: "/insights",
    locationSales: "/insights/location-sales",
  },
};
